include artifact

diff --git a/.github/workflows/TotalSalws2BigQuery_scheduler.yml b/.github/workflows/TotalSalws2BigQuery_scheduler.yml
--- a/.github/workflows/TotalSalws2BigQuery_scheduler.yml
+++ b/.github/workflows/TotalSalws2BigQuery_scheduler.yml
@@ -83,5 +83,12 @@ jobs:
           echo "Contents of 'data' directory after script execution:"
           ls -la data || echo "'data' directory does not exist."
           echo "Checking if CSV file exists at full path:"
-          ls -la data/dummy_data.csv || echo "CSV file not found."
+          ls -la data/TotalSales_*.csv || echo "CSV file not found."
         continue-on-error: true
+
+      # Upload CSV file as an artifact
+      - name: Upload CSV file as an artifact
+        uses: actions/upload-artifact@v3
+        with:
+          name: csv-file
+          path: data/TotalSales_*.csv  # Upload any CSV file generated in the 'data' directory
